<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('Countries', function($table)
        {
            $table->string('countrycode',3);
            $table->string('countryname');
            $table->primary('countrycode');
        });
        DB::table('Countries')->insert([
            ['countrycode' => 'AFG', 'countryname' => 'Afghanistan'],
            ['countrycode' => 'ALA', 'countryname' => '├àland'],
            ['countrycode' => 'ALB', 'countryname' => 'Albania'],
            ['countrycode' => 'DZA', 'countryname' => 'Algeria'],
            ['countrycode' => 'ASM', 'countryname' => 'American Samoa'],
            ['countrycode' => 'AND', 'countryname' => 'Andorra'],
            ['countrycode' => 'AGO', 'countryname' => 'Angola'],
            ['countrycode' => 'AIA', 'countryname' => 'Anguilla'],
            ['countrycode' => 'ATA', 'countryname' => 'Antarctica'],
            ['countrycode' => 'ATG', 'countryname' => 'Antigua and Barbuda'],
            ['countrycode' => 'ARG', 'countryname' => 'Argentina'],
            ['countrycode' => 'ARM', 'countryname' => 'Armenia'],
            ['countrycode' => 'ABW', 'countryname' => 'Aruba'],
            ['countrycode' => 'AUS', 'countryname' => 'Australia'],
            ['countrycode' => 'AUT', 'countryname' => 'Austria'],
            ['countrycode' => 'AZE', 'countryname' => 'Azerbaijan'],
            ['countrycode' => 'BHS', 'countryname' => 'Bahamas'],
            ['countrycode' => 'BHR', 'countryname' => 'Bahrain'],
            ['countrycode' => 'BGD', 'countryname' => 'Bangladesh'],
            ['countrycode' => 'BRB', 'countryname' => 'Barbados'],
            ['countrycode' => 'BLR', 'countryname' => 'Belarus'],
            ['countrycode' => 'BEL', 'countryname' => 'Belgium'],
            ['countrycode' => 'BLZ', 'countryname' => 'Belize'],
            ['countrycode' => 'BEN', 'countryname' => 'Benin'],
            ['countrycode' => 'BMU', 'countryname' => 'Bermuda'],
            ['countrycode' => 'BTN', 'countryname' => 'Bhutan'],
            ['countrycode' => 'BOL', 'countryname' => 'Bolivia'],
            ['countrycode' => 'BES', 'countryname' => 'Bonaire'],
            ['countrycode' => 'BIH', 'countryname' => 'Bosnia and Herzegovina'],
            ['countrycode' => 'BWA', 'countryname' => 'Botswana'],
            ['countrycode' => 'BVT', 'countryname' => 'Bouvet Island'],
            ['countrycode' => 'BRA', 'countryname' => 'Brazil'],
            ['countrycode' => 'IOT', 'countryname' => 'British Indian Ocean Territory'],
            ['countrycode' => 'VGB', 'countryname' => 'British Virgin Islands'],
            ['countrycode' => 'BRN', 'countryname' => 'Brunei'],
            ['countrycode' => 'BGR', 'countryname' => 'Bulgaria'],
            ['countrycode' => 'BFA', 'countryname' => 'Burkina Faso'],
            ['countrycode' => 'BDI', 'countryname' => 'Burundi'],
            ['countrycode' => 'KHM', 'countryname' => 'Cambodia'],
            ['countrycode' => 'CMR', 'countryname' => 'Cameroon'],
            ['countrycode' => 'CAN', 'countryname' => 'Canada'],
            ['countrycode' => 'CPV', 'countryname' => 'Cape Verde'],
            ['countrycode' => 'CYM', 'countryname' => 'Cayman Islands'],
            ['countrycode' => 'CAF', 'countryname' => 'Central African Republic'],
            ['countrycode' => 'TCD', 'countryname' => 'Chad'],
            ['countrycode' => 'CHL', 'countryname' => 'Chile'],
            ['countrycode' => 'CHN', 'countryname' => 'China'],
            ['countrycode' => 'CXR', 'countryname' => 'Christmas Island'],
            ['countrycode' => 'CCK', 'countryname' => 'Cocos [Keeling] Islands'],
            ['countrycode' => 'COL', 'countryname' => 'Colombia'],
            ['countrycode' => 'COM', 'countryname' => 'Comoros'],
            ['countrycode' => 'COK', 'countryname' => 'Cook Islands'],
            ['countrycode' => 'CRI', 'countryname' => 'Costa Rica'],
            ['countrycode' => 'HRV', 'countryname' => 'Croatia'],
            ['countrycode' => 'CUB', 'countryname' => 'Cuba'],
            ['countrycode' => 'CUW', 'countryname' => 'Curacao'],
            ['countrycode' => 'CYP', 'countryname' => 'Cyprus'],
            ['countrycode' => 'CZE', 'countryname' => 'Czech Republic'],
            ['countrycode' => 'COD', 'countryname' => 'Democratic Republic of the Congo'],
            ['countrycode' => 'DNK', 'countryname' => 'Denmark'],
            ['countrycode' => 'DJI', 'countryname' => 'Djibouti'],
            ['countrycode' => 'DMA', 'countryname' => 'Dominica'],
            ['countrycode' => 'DOM', 'countryname' => 'Dominican Republic'],
            ['countrycode' => 'TLS', 'countryname' => 'East Timor'],
            ['countrycode' => 'ECU', 'countryname' => 'Ecuador'],
            ['countrycode' => 'EGY', 'countryname' => 'Egypt'],
            ['countrycode' => 'SLV', 'countryname' => 'El Salvador'],
            ['countrycode' => 'GNQ', 'countryname' => 'Equatorial Guinea'],
            ['countrycode' => 'ERI', 'countryname' => 'Eritrea'],
            ['countrycode' => 'EST', 'countryname' => 'Estonia'],
            ['countrycode' => 'ETH', 'countryname' => 'Ethiopia'],
            ['countrycode' => 'FLK', 'countryname' => 'Falkland Islands'],
            ['countrycode' => 'FRO', 'countryname' => 'Faroe Islands'],
            ['countrycode' => 'FJI', 'countryname' => 'Fiji'],
            ['countrycode' => 'FIN', 'countryname' => 'Finland'],
            ['countrycode' => 'FRA', 'countryname' => 'France'],
            ['countrycode' => 'GUF', 'countryname' => 'French Guiana'],
            ['countrycode' => 'PYF', 'countryname' => 'French Polynesia'],
            ['countrycode' => 'ATF', 'countryname' => 'French Southern Territories'],
            ['countrycode' => 'GAB', 'countryname' => 'Gabon'],
            ['countrycode' => 'GMB', 'countryname' => 'Gambia'],
            ['countrycode' => 'GEO', 'countryname' => 'Georgia'],
            ['countrycode' => 'DEU', 'countryname' => 'Germany'],
            ['countrycode' => 'GHA', 'countryname' => 'Ghana'],
            ['countrycode' => 'GIB', 'countryname' => 'Gibraltar'],
            ['countrycode' => 'GRC', 'countryname' => 'Greece'],
            ['countrycode' => 'GRL', 'countryname' => 'Greenland'],
            ['countrycode' => 'GRD', 'countryname' => 'Grenada'],
            ['countrycode' => 'GLP', 'countryname' => 'Guadeloupe'],
            ['countrycode' => 'GUM', 'countryname' => 'Guam'],
            ['countrycode' => 'GTM', 'countryname' => 'Guatemala'],
            ['countrycode' => 'GGY', 'countryname' => 'Guernsey'],
            ['countrycode' => 'GIN', 'countryname' => 'Guinea'],
            ['countrycode' => 'GNB', 'countryname' => 'Guinea-Bissau'],
            ['countrycode' => 'GUY', 'countryname' => 'Guyana'],
            ['countrycode' => 'HTI', 'countryname' => 'Haiti'],
            ['countrycode' => 'HMD', 'countryname' => 'Heard Island and McDonald Islands'],
            ['countrycode' => 'HND', 'countryname' => 'Honduras'],
            ['countrycode' => 'HKG', 'countryname' => 'Hong Kong'],
            ['countrycode' => 'HUN', 'countryname' => 'Hungary'],
            ['countrycode' => 'ISL', 'countryname' => 'Iceland'],
            ['countrycode' => 'IND', 'countryname' => 'India'],
            ['countrycode' => 'IDN', 'countryname' => 'Indonesia'],
            ['countrycode' => 'IRN', 'countryname' => 'Iran'],
            ['countrycode' => 'IRQ', 'countryname' => 'Iraq'],
            ['countrycode' => 'IRL', 'countryname' => 'Ireland'],
            ['countrycode' => 'IMN', 'countryname' => 'Isle of Man'],
            ['countrycode' => 'ISR', 'countryname' => 'Israel'],
            ['countrycode' => 'ITA', 'countryname' => 'Italy'],
            ['countrycode' => 'CIV', 'countryname' => 'Ivory Coast'],
            ['countrycode' => 'JAM', 'countryname' => 'Jamaica'],
            ['countrycode' => 'JPN', 'countryname' => 'Japan'],
            ['countrycode' => 'JEY', 'countryname' => 'Jersey'],
            ['countrycode' => 'JOR', 'countryname' => 'Jordan'],
            ['countrycode' => 'KAZ', 'countryname' => 'Kazakhstan'],
            ['countrycode' => 'KEN', 'countryname' => 'Kenya'],
            ['countrycode' => 'KIR', 'countryname' => 'Kiribati'],
            ['countrycode' => 'XKX', 'countryname' => 'Kosovo'],
            ['countrycode' => 'KWT', 'countryname' => 'Kuwait'],
            ['countrycode' => 'KGZ', 'countryname' => 'Kyrgyzstan'],
            ['countrycode' => 'LAO', 'countryname' => 'Laos'],
            ['countrycode' => 'LVA', 'countryname' => 'Latvia'],
            ['countrycode' => 'LBN', 'countryname' => 'Lebanon'],
            ['countrycode' => 'LSO', 'countryname' => 'Lesotho'],
            ['countrycode' => 'LBR', 'countryname' => 'Liberia'],
            ['countrycode' => 'LBY', 'countryname' => 'Libya'],
            ['countrycode' => 'LIE', 'countryname' => 'Liechtenstein'],
            ['countrycode' => 'LTU', 'countryname' => 'Lithuania'],
            ['countrycode' => 'LUX', 'countryname' => 'Luxembourg'],
            ['countrycode' => 'MAC', 'countryname' => 'Macao'],
            ['countrycode' => 'MKD', 'countryname' => 'Macedonia'],
            ['countrycode' => 'MDG', 'countryname' => 'Madagascar'],
            ['countrycode' => 'MWI', 'countryname' => 'Malawi'],
            ['countrycode' => 'MYS', 'countryname' => 'Malaysia'],
            ['countrycode' => 'MDV', 'countryname' => 'Maldives'],
            ['countrycode' => 'MLI', 'countryname' => 'Mali'],
            ['countrycode' => 'MLT', 'countryname' => 'Malta'],
            ['countrycode' => 'MHL', 'countryname' => 'Marshall Islands'],
            ['countrycode' => 'MTQ', 'countryname' => 'Martinique'],
            ['countrycode' => 'MRT', 'countryname' => 'Mauritania'],
            ['countrycode' => 'MUS', 'countryname' => 'Mauritius'],
            ['countrycode' => 'MYT', 'countryname' => 'Mayotte'],
            ['countrycode' => 'MEX', 'countryname' => 'Mexico'],
            ['countrycode' => 'FSM', 'countryname' => 'Micronesia'],
            ['countrycode' => 'MDA', 'countryname' => 'Moldova'],
            ['countrycode' => 'MCO', 'countryname' => 'Monaco'],
            ['countrycode' => 'MNG', 'countryname' => 'Mongolia'],
            ['countrycode' => 'MNE', 'countryname' => 'Montenegro'],
            ['countrycode' => 'MSR', 'countryname' => 'Montserrat'],
            ['countrycode' => 'MAR', 'countryname' => 'Morocco'],
            ['countrycode' => 'MOZ', 'countryname' => 'Mozambique'],
            ['countrycode' => 'MMR', 'countryname' => 'Myanmar [Burma]'],
            ['countrycode' => 'NAM', 'countryname' => 'Namibia'],
            ['countrycode' => 'NRU', 'countryname' => 'Nauru'],
            ['countrycode' => 'NPL', 'countryname' => 'Nepal'],
            ['countrycode' => 'NLD', 'countryname' => 'Netherlands'],
            ['countrycode' => 'NCL', 'countryname' => 'New Caledonia'],
            ['countrycode' => 'NZL', 'countryname' => 'New Zealand'],
            ['countrycode' => 'NIC', 'countryname' => 'Nicaragua'],
            ['countrycode' => 'NER', 'countryname' => 'Niger'],
            ['countrycode' => 'NGA', 'countryname' => 'Nigeria'],
            ['countrycode' => 'NIU', 'countryname' => 'Niue'],
            ['countrycode' => 'NFK', 'countryname' => 'Norfolk Island'],
            ['countrycode' => 'PRK', 'countryname' => 'North Korea'],
            ['countrycode' => 'MNP', 'countryname' => 'Northern Mariana Islands'],
            ['countrycode' => 'NOR', 'countryname' => 'Norway'],
            ['countrycode' => 'OMN', 'countryname' => 'Oman'],
            ['countrycode' => 'PAK', 'countryname' => 'Pakistan'],
            ['countrycode' => 'PLW', 'countryname' => 'Palau'],
            ['countrycode' => 'PSE', 'countryname' => 'Palestine'],
            ['countrycode' => 'PAN', 'countryname' => 'Panama'],
            ['countrycode' => 'PNG', 'countryname' => 'Papua New Guinea'],
            ['countrycode' => 'PRY', 'countryname' => 'Paraguay'],
            ['countrycode' => 'PER', 'countryname' => 'Peru'],
            ['countrycode' => 'PHL', 'countryname' => 'Philippines'],
            ['countrycode' => 'PCN', 'countryname' => 'Pitcairn Islands'],
            ['countrycode' => 'POL', 'countryname' => 'Poland'],
            ['countrycode' => 'PRT', 'countryname' => 'Portugal'],
            ['countrycode' => 'PRI', 'countryname' => 'Puerto Rico'],
            ['countrycode' => 'QAT', 'countryname' => 'Qatar'],
            ['countrycode' => 'COG', 'countryname' => 'Republic of the Congo'],
            ['countrycode' => 'REU', 'countryname' => 'R├⌐union'],
            ['countrycode' => 'ROU', 'countryname' => 'Romania'],
            ['countrycode' => 'RUS', 'countryname' => 'Russia'],
            ['countrycode' => 'RWA', 'countryname' => 'Rwanda'],
            ['countrycode' => 'BLM', 'countryname' => 'Saint Barth├⌐lemy'],
            ['countrycode' => 'SHN', 'countryname' => 'Saint Helena'],
            ['countrycode' => 'KNA', 'countryname' => 'Saint Kitts and Nevis'],
            ['countrycode' => 'LCA', 'countryname' => 'Saint Lucia'],
            ['countrycode' => 'MAF', 'countryname' => 'Saint Martin'],
            ['countrycode' => 'SPM', 'countryname' => 'Saint Pierre and Miquelon'],
            ['countrycode' => 'VCT', 'countryname' => 'Saint Vincent and the Grenadines'],
            ['countrycode' => 'WSM', 'countryname' => 'Samoa'],
            ['countrycode' => 'SMR', 'countryname' => 'San Marino'],
            ['countrycode' => 'STP', 'countryname' => 'S├úo Tom├⌐ and Pr├¡ncipe'],
            ['countrycode' => 'SAU', 'countryname' => 'Saudi Arabia'],
            ['countrycode' => 'SEN', 'countryname' => 'Senegal'],
            ['countrycode' => 'SRB', 'countryname' => 'Serbia'],
            ['countrycode' => 'SYC', 'countryname' => 'Seychelles'],
            ['countrycode' => 'SLE', 'countryname' => 'Sierra Leone'],
            ['countrycode' => 'SGP', 'countryname' => 'Singapore'],
            ['countrycode' => 'SXM', 'countryname' => 'Sint Maarten'],
            ['countrycode' => 'SVK', 'countryname' => 'Slovakia'],
            ['countrycode' => 'SVN', 'countryname' => 'Slovenia'],
            ['countrycode' => 'SLB', 'countryname' => 'Solomon Islands'],
            ['countrycode' => 'SOM', 'countryname' => 'Somalia'],
            ['countrycode' => 'ZAF', 'countryname' => 'South Africa'],
            ['countrycode' => 'SGS', 'countryname' => 'South Georgia and the South Sandwich Islands'],
            ['countrycode' => 'KOR', 'countryname' => 'South Korea'],
            ['countrycode' => 'SSD', 'countryname' => 'South Sudan'],
            ['countrycode' => 'ESP', 'countryname' => 'Spain'],
            ['countrycode' => 'LKA', 'countryname' => 'Sri Lanka'],
            ['countrycode' => 'SDN', 'countryname' => 'Sudan'],
            ['countrycode' => 'SUR', 'countryname' => 'Suriname'],
            ['countrycode' => 'SJM', 'countryname' => 'Svalbard and Jan Mayen'],
            ['countrycode' => 'SWZ', 'countryname' => 'Swaziland'],
            ['countrycode' => 'SWE', 'countryname' => 'Sweden'],
            ['countrycode' => 'CHE', 'countryname' => 'Switzerland'],
            ['countrycode' => 'SYR', 'countryname' => 'Syria'],
            ['countrycode' => 'TWN', 'countryname' => 'Taiwan'],
            ['countrycode' => 'TJK', 'countryname' => 'Tajikistan'],
            ['countrycode' => 'TZA', 'countryname' => 'Tanzania'],
            ['countrycode' => 'THA', 'countryname' => 'Thailand'],
            ['countrycode' => 'TGO', 'countryname' => 'Togo'],
            ['countrycode' => 'TKL', 'countryname' => 'Tokelau'],
            ['countrycode' => 'TON', 'countryname' => 'Tonga'],
            ['countrycode' => 'TTO', 'countryname' => 'Trinidad and Tobago'],
            ['countrycode' => 'TUN', 'countryname' => 'Tunisia'],
            ['countrycode' => 'TUR', 'countryname' => 'Turkey'],
            ['countrycode' => 'TKM', 'countryname' => 'Turkmenistan'],
            ['countrycode' => 'TCA', 'countryname' => 'Turks and Caicos Islands'],
            ['countrycode' => 'TUV', 'countryname' => 'Tuvalu'],
            ['countrycode' => 'UMI', 'countryname' => 'U.S. Minor Outlying Islands'],
            ['countrycode' => 'VIR', 'countryname' => 'U.S. Virgin Islands'],
            ['countrycode' => 'UGA', 'countryname' => 'Uganda'],
            ['countrycode' => 'UKR', 'countryname' => 'Ukraine'],
            ['countrycode' => 'ARE', 'countryname' => 'United Arab Emirates'],
            ['countrycode' => 'GBR', 'countryname' => 'United Kingdom'],
            ['countrycode' => 'USA', 'countryname' => 'United States'],
            ['countrycode' => 'URY', 'countryname' => 'Uruguay'],
            ['countrycode' => 'UZB', 'countryname' => 'Uzbekistan'],
            ['countrycode' => 'VUT', 'countryname' => 'Vanuatu'],
            ['countrycode' => 'VAT', 'countryname' => 'Vatican City'],
            ['countrycode' => 'VEN', 'countryname' => 'Venezuela'],
            ['countrycode' => 'VNM', 'countryname' => 'Vietnam'],
            ['countrycode' => 'WLF', 'countryname' => 'Wallis and Futuna'],
            ['countrycode' => 'ESH', 'countryname' => 'Western Sahara'],
            ['countrycode' => 'YEM', 'countryname' => 'Yemen'],
            ['countrycode' => 'ZMB', 'countryname' => 'Zambia'],
            ['countrycode' => 'ZWE', 'countryname' => 'Zimbabwe'],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('Countries');
    }
}
